#ifndef CONFIG_H
#define CONFIG_H

/* 宏控制编译示例 */
#define SUM_EXAMPLE
#define COMPARE_EXAMPLE
// #define USE_SCANF_EXAMPLE
#define FACTORIAL_EXAMPLE
#define GET_VALUE_EXAMPLE
#define IS_PRIME_EXAMPLE
#define FAHRENHEIT_TO_CELSIUS_EXAMPLE
#define TEST_ESCAPE_CHARACTERS_EXAMPLE



#endif // CONFIG_H